<script lang="ts" setup>
const languageToSurveyUrl: Record<string, string> = {
  Abkhazian: "https://forms.cloud.microsoft/e/pdmAKbsRk1",
  Achinese: "",
  Adyghe: "",
  Afar: "",
  Afrikaans: "",
  Albanian: "",
  "Albanian, Tosk": "",
  "Altai, Southern": "",
  Amharic: "",
  Amis: "",
  Angika: "",
  Arabic: "",
  "Arabic, Egyptian": "",
  "Arabic, Moroccan": "",
  Aragonese: "",
  Aramaic: "",
  Armenian: "",
  "Armenian, Western": "",
  Arpitan: "",
  Assamese: "",
  Asturian: "",
  Atayal: "",
  Atikamekw: "",
  Avaric: "",
  Avestan: "",
  Awadhi: "",
  Aymara: "",
  Azerbaijani: "",
  "Azerbaijani, South": "",
  Balinese: "",
  Bambara: "",
  Banjar: "",
  Bashkir: "https://forms.cloud.microsoft/e/HLahp4Q5X6",
  Basque: "",
  Bavarian: "",
  Belarusian: "",
  Bengali: "",
  Bishnupriya: "",
  Bislama: "",
  "Bokmål, Norwegian": "",
  Bosnian: "",
  Breton: "",
  Buginese: "",
  Bulgarian: "",
  "Buriat, Russia": "",
  Burmese: "",
  Catalan: "",
  Cebuano: "",
  "Central, Bikol": "",
  Chamorro: "",
  Chechen: "",
  Cherokee: "",
  Cheyenne: "",
  Chichewa: "",
  "Chinese, Gan": "",
  "Chinese, Hakka": "",
  "Chinese, Min Dong": "",
  "Chinese, Simplified": "https://forms.cloud.microsoft/e/XjSq1DqJ7c",
  "Chinese, Traditional": "https://forms.cloud.microsoft/e/0FPvLqZaEu",
  "Chinese, Wu": "",
  Chuvash: "",
  Cornish: "",
  Corsican: "",
  Cree: "",
  "Creole English, Jamaican": "",
  "Creole French, Guianese": "",
  Croatian: "",
  Czech: "",
  Dagbani: "",
  Danish: "https://forms.cloud.microsoft/e/bd7bh4HdwN",
  Dimli: "",
  Dinka: "",
  Divehi: "",
  Dotyali: "",
  Dutch: "https://forms.cloud.microsoft/e/SG7CiQ0tHD",
  Dzongkha: "",
  "English, American": "https://forms.cloud.microsoft/e/srqTJmuZmx",
  "English, Old": "",
  Erzya: "",
  Esperanto: "",
  Estonian: "",
  Ewe: "",
  Extremaduran: "",
  Fanti: "",
  Farefare: "",
  Faroese: "https://forms.cloud.microsoft/e/9dwvhqsCJz",
  Fijian: "",
  Finnish: "https://forms.cloud.microsoft/e/EvPHfYqEpJ",
  Fon: "",
  French: "https://forms.cloud.microsoft/e/D0USRptpdk",
  "Frisian, Northern": "",
  "Frisian, Western": "",
  Friulian: "",
  Fulah: "",
  Gaelic: "",
  Gagauz: "",
  Galician: "",
  Ganda: "",
  Georgian: "",
  German: "https://forms.cloud.microsoft/e/j0gSH5wd2n",
  "German, Low": "",
  "German, Pennsylvania": "",
  Gilaki: "",
  Gorontalo: "",
  Gothic: "",
  Greek: "https://forms.cloud.microsoft/e/PSmAYeeYKj",
  Greenlandic: "",
  Guarani: "",
  Gujarati: "",
  Gun: "",
  Haitian: "",
  Hausa: "",
  Hawaiian: "",
  Hebrew: "",
  Herero: "",
  Hindi: "",
  "Hindi, Fiji": "",
  Hungarian: "",
  Icelandic: "https://forms.cloud.microsoft/e/u5NfqfXuWw",
  Ido: "",
  Igbo: "",
  Iloko: "",
  Indonesian: "",
  Ingush: "",
  Interlingua: "",
  Interlingue: "",
  Inuktitut: "",
  Inupiaq: "",
  Irish: "",
  Italian: "",
  Japanese: "",
  Kabardian: "",
  Kabiyè: "",
  Kabyle: "",
  Kalmyk: "",
  Kannada: "",
  Kanuri: "",
  "Karachay-Balkar": "",
  "Kara-Kalpak": "",
  Kashmiri: "",
  Kashubian: "",
  Kazakh: "",
  "Khmer, Central": "",
  Kikuyu: "",
  Kinyarwanda: "",
  Kirghiz: "",
  Kölsch: "",
  Komi: "",
  "Komi-Permyak": "",
  Kongo: "",
  "Konkani, Goan": "",
  Korean: "",
  Kotava: "",
  Kuanyama: "",
  Kurdish: "",
  "Kurdish, Central": "",
  Ladin: "",
  Ladino: "",
  Lak: "",
  Lao: "",
  Latgalian: "",
  Latin: "",
  Latvian: "https://forms.cloud.microsoft/e/kFGmjbZYLt",
  Lezghian: "",
  Ligurian: "",
  Limburgan: "",
  Lingala: "",
  "Lingua Franca Nova": "",
  Lithuanian: "https://forms.cloud.microsoft/e/TKQFMNfXZc",
  Livvi: "",
  Lojban: "",
  Lombard: "",
  "Luba-Katanga": "",
  Luxembourgish: "",
  Macedonian: "",
  Madurese: "",
  Maithili: "",
  Malagasy: "",
  Malay: "",
  Malayalam: "",
  Maltese: "",
  Manipuri: "",
  Manx: "",
  Maori: "",
  Marathi: "",
  "Mari, Eastern": "",
  "Mari, Western": "",
  Marshallese: "",
  Mazanderani: "",
  Minangkabau: "",
  Mingrelian: "",
  Mirandese: "",
  Moksha: "",
  Mon: "",
  Mongolian: "",
  "Motu, Hiri": "",
  Narom: "",
  Nauru: "",
  Navajo: "",
  "Ndebele, Northern": "",
  "Ndebele, South": "",
  Ndonga: "",
  Neapolitan: "",
  Nepali: "",
  Newari: "",
  Nias: "",
  "N'Ko": "",
  "Norwegian Bokmål": "https://forms.cloud.microsoft/e/Md0QX4Yx8A",
  "Norwegian Nynorsk": "https://forms.cloud.microsoft/e/vUAsjGUU4i",
  Novial: "",
  Occitan: "",
  Ojibwa: "",
  Oriya: "",
  Oromo: "",
  Ossetian: "",
  Paiwan: "",
  Pali: "",
  Pampanga: "",
  Pangasinan: "",
  "Panjabi, Western": "",
  "Pa'O": "",
  Papiamento: "",
  Pashto: "",
  Persian: "",
  Pfaelzisch: "",
  Picard: "",
  "Pidgin English, Ghanaian": "",
  "Pidgin, Nigerian": "",
  Piemontese: "",
  "Pitcairn-Norfolk": "",
  Polish: "https://forms.cloud.microsoft/e/vrXFzLiRwN",
  Pontic: "",
  Portuguese: "https://forms.cloud.microsoft/e/mSBaZghhJ3",
  Punjabi: "",
  Quechua: "",
  "Romani, Vlax": "",
  Romanian: "",
  Romansh: "",
  Rundi: "",
  Russian: "https://forms.cloud.microsoft/e/5DeJu1EZCB",
  Rusyn: "",
  Sakizaya: "",
  "Sami, Inari": "",
  "Sami, Northern": "",
  Samoan: "",
  Sango: "",
  Sanskrit: "",
  Santali: "",
  Saraiki: "",
  Sardinian: "",
  Saterfriesisch: "",
  "Saxon, Low": "",
  Scots: "",
  Serbian: "",
  Shan: "",
  Shona: "",
  Sicilian: "",
  Silesian: "",
  Sindhi: "",
  Sinhala: "",
  "Slavic, Church": "",
  Slovak: "",
  Slovenian: "",
  Somali: "",
  "Sorbian, Lower": "",
  "Sorbian, Upper": "",
  Sotho: "",
  "Sotho, Northern": "",
  Spanish: "",
  Sundanese: "",
  Swahili: "",
  Swati: "",
  Swedish: "https://forms.cloud.microsoft/e/4vhPdYzXqw",
  Tachelhit: "",
  Tagalog: "",
  Tahitian: "",
  Tajik: "",
  Talysh: "",
  Tamil: "",
  Taroko: "",
  Tatar: "https://forms.cloud.microsoft/e/3diVuJcWgS",
  "Tatar, Crimean": "",
  Telugu: "",
  Tetum: "",
  Thai: "",
  Tibetan: "",
  Tigrinya: "",
  "Tok Pisin": "",
  Tonga: "",
  "Tongo, Sranan": "",
  Tsonga: "",
  Tswana: "",
  Tulu: "",
  Tumbuka: "",
  Turkish: "https://forms.cloud.microsoft/e/L7PBNTra3P",
  Turkmen: "",
  Tuvinian: "",
  Twi: "",
  Tyap: "",
  Udmurt: "",
  Uighur: "",
  Ukrainian: "https://forms.cloud.microsoft/e/N2KJPx4bpK",
  Urdu: "https://forms.cloud.microsoft/e/MQdX7dzTpX",
  Uzbek: "",
  Venda: "",
  Venetian: "",
  Veps: "",
  Vietnamese: "",
  Vlaams: "",
  Volapük: "",
  Walloon: "",
  Waray: "",
  Wayuu: "",
  Welsh: "",
  Wolof: "",
  Xhosa: "",
  Yakut: "",
  "Yi, Sichuan": "",
  Yiddish: "",
  Yoruba: "",
  Zeeuws: "",
  Zhuang: "",
  Zulu: "",
};

function goToSurvey() {
  const selectElement = document.getElementById(
    "language-select",
  ) as HTMLSelectElement;
  const selectedLanguage = selectElement.value;
  const surveyUrl = languageToSurveyUrl[selectedLanguage];
  if (surveyUrl) {
    window.open(surveyUrl, "_blank");
  } else {
    window.open(
      "mailto:dan.smart@alexandra.dk?" +
        "subject=Fluency%20Survey%20Language%20Support - " +
        selectedLanguage +
        "&" +
        "body=I would like to request support for " +
        selectedLanguage +
        " in the fluency survey. Thanks!",
      "_blank",
    );
  }
}
</script>

<template>
  <h1 class="centered">Feedback on the Fluency of LLMs</h1>
  <p class="centered-box serif-text">
    Thanks for your interest in providing feedback on the fluency of LLMs! The
    survey should only take about 5 minutes to complete. Please select a
    language which you are fluent in.
  </p>

  <br />
  <br />

  <div class="centered">
    <label for="language-select" class="language-label"
      >Select Language:
    </label>
    <select id="language-select" class="dropdown">
      <option
        v-for="language in Object.keys(languageToSurveyUrl)"
        v-bind:key="language"
        :value="language"
      >
        {{ language }}
      </option>
    </select>
    <button class="button" @click="goToSurvey">Go to Survey</button>
  </div>
</template>

<style scoped>
h1 {
  font-size: 3rem;
}
.language-label {
  font-size: 1.2rem;
  margin-right: 10px;
}
.dropdown {
  font-size: 1rem;
  padding: 5px;
  margin-right: 20px;
  border: 1px solid #ccc;
  border-radius: 4px;
}
.button {
  font-size: 1rem;
  padding: 10px 20px;
  color: white;
  background-color: #4a90e2;
  border: none;
  border-radius: 4px;
  cursor: pointer;
}
.button:hover {
  background-color: #357abd;
}
</style>
